- name: Running Consul
  docker:
    image: progrium/consul
    name: consul
    hostname: "{{ ansible_hostname }}"
    ports:
      - 8300:8300
      - 8301:8301
      - 8301:8301/udp
      - 8500:8500
    command: -advertise {{ consul_master_ip }} {{ consul_extra }}
  tags: [consul]
