- name: Running Swarm node 
  docker:
    name: swarm-node
    image: swarm
    command: join --advertise={{ inventory_hostname }}:2375 consul://{{ consul_master_ip }}:8500
    env:
      SERVICE_NAME: swarm-node
  when: swarm_master is undefined
  tags: [swarm]

- name: Running Swarm master 
  docker:
    name: swarm-master
    image: swarm
    ports: 3375:2375
    command: manage consul://{{ consul_master_ip }}:8500
    env:
      SERVICE_NAME: swarm-master
  when: swarm_master is defined
  tags: [swarm]
